### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jorfermo** [eosnewyork/eospy#13]
OS: MacOS 10.13.6
Python 3.6.5
```
$wget https://raw.githubusercontent.com/eosnewyork/eospy/master/examples/push_transaction.py
$python3 push_transaction.py
Traceback (most recent call last):
  File "push_transaction.py", line 35, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "/usr/local/lib/python3.6/site-packages/eospy/cleos.py", line 159, in push_transaction
    signatures.append(k.sign(digest))
  File "/usr/local/lib/python3.6/site-packages/eospy/keys.py", line 187, in sign
    return 'SIG_K1_' + self._check_encode(hexlify(sigstr), 'K1').decode()
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by deckb** [comment]
Sorry I haven't had a chance to steal the development mac for testing yet. I am scheduling some time during this weekends hackathon to take a look.

**Comment by deckb** [comment]
I just tried on mac with 2.7 and 3.7 and it worked. Can you upgrade from 3.6 -> 3.7 and attempt again?

**Comment by jorfermo** [comment]
Got and exception but it seems to be related to your test network:

````
$ python3 push_transaction.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/eospy/dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://api.pennstation.eosnewyork.io:7001/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "push_transaction.py", line 35, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "/usr/local/lib/python3.7/site-packages/eospy/cleos.py", line 169, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data)
  File "/usr/local/lib/python3.7/site-packages/eospy/cleos.py", line 31, in post
    return cmd.post_url(url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eospy/dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure', 'details': [{'message': 'assertion failure with message: to account does not exist', 'file': 'wasm_interface.cpp', 'line_number': 934, 'method': 'eosio_assert'}, {'message': 'pending console output: ', 'file': 'apply_context.cpp', 'line_number': 72, 'method': 'exec_one'}]}}
```

**Comment by deckb** [comment]
Yes that is because the testnet wasn't setup correctly. It looks like 3.7 works with the lib but 3.6.5 doesn't. I'll take a deeper look and see if I can fix it for 3.6

**Comment by HFFP** [comment]
my python version is 3.6.5, does't work in mac os 10.13.4, but work in ubuntu 16.04.4 LTS.

`# new key
new_key = ce.create_key()

print(new_key.to_public())`

**Comment by HFFP** [comment]
my python version is 3.6.5, does't work in mac os 10.13.4, but work in ubuntu 16.04.4 LTS.
```
# new key
new_key = ce.create_key()

print(new_key.to_public())
```

**Comment by hurlenko** [comment]
```
Python 3.6.5
libeospy==2.0.0
base58==0.2.5
```
Had the same issue. The problem is in [base58.b58encode](https://github.com/eosnewyork/eospy/blob/c9b49f727e952a742902df9ba098dc6e21cdeb5e/eospy/keys.py#L71) function. I returns a string which cannot be decode in methods like `to_wif`, `to_public` etc. Maybe you should pinn versions for all dependencies in `setup.py`? Updating to `base58==1.0.3` solved my issue

**Comment by deckb** [comment]
Good catch. I pinned to >= 1.0.3 in version 2.0.1
