### ISSUE TITLE
3.6.5 unsupported operand types for & 'float' and 'int'

### ISSUE THREAD

**Issue by deckb** [eosnewyork/eospy#20]
> @jerryfane this should be fixed in 1.1.7. Can you confirm that?
> 
> @plimerence I'm taking a look now. Hopefully should have a fix shortly.

I've just tried but I get this error every time I try to push a transaction now.. 

```
Traceback (most recent call last):
  File "pycleos.py", line 51, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\cleos.py", line 147, in push_transaction
    digest = sig_digest(trx.encode(), chain_info['chain_id'])
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 202, in encode
    actions = self._encode_buffer(self.actions)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 85, in _encode_buffer
    return EOSBuffer(value).encode()
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 266, in encode
    e_item = self.encode(item)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 262, in encode
    return val.encode()
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 109, in encode
    data_len = self._encode_buffer(VarUInt(len(self.data)/2))
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 85, in _encode_buffer
    return EOSBuffer(value).encode()
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 255, in encode
    return self._write_varuint(val)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 229, in _write_varuint
    buf = vuint.encode()
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 56, in encode
    buf = int((val) & 0x7f)
TypeError: unsupported operand type(s) for &: 'float' and 'int'
```

I'm using Windows 10, python 3.6.5 and eospy 1.1.7 (just updated)

_Originally posted by @jerryfane in https://github.com/eosnewyork/eospy/issues/19#issuecomment-450434069_

**Comment by deckb** [comment]
@jerryfane 1.1.8 should contain the fix for you. Please confirm and I will close this issue.

**Comment by jerryfane** [comment]
Worked fine for 2 transactions, then this new error appeared...

```
Traceback (most recent call last):
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://eos.greymass.com/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycleos.py", line 51, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\cleos.py", line 169, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\cleos.py", line 31, in post
    return cmd.post_url(url, **kwargs)
  File "C:\Users\Jerry\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure', 'details': [{'message': 'assertion failure with message: unable to find key', 'file': 'wasm_interface.cpp', 'line_number': 917, 'method': 'eosio_assert'}, {'message': 'pending console output: ', 'file': 'apply_context.cpp', 'line_number': 72, 'method': 'exec_one'}]}}

```

**assertion failure with message: unable to find key**

**Comment by deckb** [comment]
Can you share what you are trying to do? If it was the same call and it failed the 3rd time it may be an issue with your setup. Others have had similar issues: 
https://github.com/EOSIO/eos/issues/3653

**Comment by jerryfane** [comment]
I'm just trying to send a simple token transfer in the mainnet, you can check my code here, it's basically the same as the example in this git. 

```
from eospy.cleos import Cleos
import eospy.keys

ce = Cleos(url='https://eos.greymass.com')

key = eospy.keys.EOSKey('MYPRIVATEKEY')

memo = "{'type': 'sell-limit', 'symbol': 'parslseed123-seed-eos', 'price': '0.00124', 'channel': 'API'}"

payload = [
        {
            'args': {
                "from": "myaccount",             # sender
                "to": "receiveraccount,               # receiver
                "quantity": "0.0001 EPRA",           # In EOS
                "memo": str(memo),
            },
            "account": "eosio.token",
            "name": "transfer",
            "authorization": [{
                "actor": "myaccount",
                "permission": "active",
            }],
        }
    ]

#payload[0]['args']['memo'] = str(memo)
print(payload[0]['args']['memo'])
print(payload[0]['args']['quantity'])

#print(memo[0]['type'])

#Converting payload to binary
data=ce.abi_json_to_bin(payload[0]['account'],payload[0]['name'],payload[0]['args'])
#Inserting payload binary form as "data" field in original payload
payload[0]['data']=data['binargs']
#Removing the arguments field
payload[0].pop('args')
#final transaction formed
trx = {"actions":[payload[0]]}

resp = ce.push_transaction(trx, key, broadcast=True)
print(resp)

```
I've tried with many tokens and amounts

**Comment by jerryfane** [comment]
You can close this thread.
The **assertion failure with message: unable to find key** was due to an error on my code. I was trying to transfer non EOS token by using the eosio.token contract. Now everything is working, thank you for your time!

**Comment by deckb** [comment]
Thanks and I apologize for not getting back to you in a timely manner.
