### ISSUE TITLE
won't run on qpython3 for Android

### ISSUE THREAD

**Issue by aboalhassan1** [eosnewyork/eospy#21]
when running setup.py i get

/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/projects3/eospy-1/0000000/eospy-1.1.8/.last_tmp.py" && exit
.1.8/.last_tmp.py" && exit          <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects3/eospy-1/0000000/eospy-1.1.8/.last_tmp.py", line 11, in <module>
    packages=find_packages(),
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/setuptools-1.1-py3.2.egg/setuptools/__init__.py", line 38, in find_packages
OSError: [Errno 13] Permission denied: '.'

**Comment by deckb** [comment]
I'm not very familiar with qpython3 but that looks like a permission issue. Is there an option to run sudo or as root? I found this similar issue which may help:

https://github.com/qpython-android/qpython3/issues/41
