### ISSUE TITLE
example `push_transaction.py`doesn't work. python3.7

### ISSUE THREAD

**Issue by ChzenChzen** [eosnewyork/eospy#27]
I've just install lib through pip and got error:

`Traceback (most recent call last):
  File "/Users/chzchz/Documents/PycharmProjects/fastwin/test.py", line 53, in <module>
    push_transaction()
  File "/Users/chzchz/Documents/PycharmProjects/fastwin/test.py", line 39, in push_transaction
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "/Users/chzchz/Documents/PycharmProjects/fastwin/venv/lib/python3.7/site-packages/eospy/cleos.py", line 169, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "/Users/chzchz/Documents/PycharmProjects/fastwin/venv/lib/python3.7/site-packages/eospy/cleos.py", line 31, in post
    return cmd.post_url(url, **kwargs)
  File "/Users/chzchz/Documents/PycharmProjects/fastwin/venv/lib/python3.7/site-packages/eospy/dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3090003, 'name': 'unsatisfied_authorization', 'what': 'Provided keys, permissions, and delays do not satisfy declared authorizations', 'details': [{'message': 'transaction declares authority \'{"actor":"eosio","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS6E8LytbBDmgA81kdfsacZCJ4sfXx5nRrVAoZTEj2kA6oUx5vGhn4"], and a delay max limit of 3888000000 ms', 'file': 'authorization_manager.cpp', 'line_number': 520, 'method': 'check_authorization'}]}}
`

but it works with old version of lib

**Comment by deckb** [comment]
I just attempted the example with 3.7 and did not have any issues. That being said the example pushes to a testnet that is not very stable at the moment and that could very likely be the issue. If you can try again and let me know if there was any issues. If there are issues please post the time you attempted to push the transaction and I'll look at the log

**Comment by deckb** [comment]
Closing with no response.
