### ISSUE TITLE
Transaction can not be pushed

### ISSUE THREAD

**Issue by ShilazTech** [eosnewyork/eospy#29]
I tried to send my transaction to "dice" token but it fails with below message

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E909F86630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.pennstation.eosnewyork.io', port=7001): Max retries exceeded with url: /v1/chain/abi_json_to_bin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E909F86630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/eos.py", line 21, in <module>
    data=ce.abi_json_to_bin(payload['account'],payload['name'],arguments)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\eospy\cleos.py", line 192, in abi_json_to_bin
    return self.post('chain.abi_json_to_bin', params=None, json=json, timeout=timeout)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\eospy\cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\eospy\dynamic_url.py", line 39, in post_url
    r = requests.post(url,params=params, json=json, data=data, timeout=timeout)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.pennstation.eosnewyork.io', port=7001): Max retries exceeded with url: /v1/chain/abi_json_to_bin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E909F86630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Process finished with exit code 1

**Comment by deckb** [comment]
That looks like a connection issue. What url are you using?

**Comment by ShilazTech** [comment]
I am using default as given in your code

ce = eospy.cleos.Cleos(url='http://api.pennstation.eosnewyork.io:7001')

**Comment by deckb** [comment]
The http://api.pennstation.eosnewyork.io:7001 endpoint is to a testnet that has been having problems lately. I would suggest using the proxy that was developed by a community member as your endpoint: https://proxy.eosnode.tools. You can find more information at https://eosnode.tools/proxy

**Comment by ShilazTech** [comment]
Hello Deckb, below is my payload

payload  = {
            "account": "eosio.token",
            "name": "transfer",
            "authorization": [{
                "actor": "gi2dimrtgmge",
                "permission": "owner",
            }],
        }

**Comment by ShilazTech** [comment]
I changed "betdiceadmin" to "bet" and now I am  receiving below error

"C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\Scripts\python.exe" "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/eos.py"
Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://api.pennstation.eosnewyork.io:7001/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/eos.py", line 31, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 173, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3040000, 'name': 'transaction_exception', 'what': 'Transaction exception', 'details': [{'message': "action's authorizing actor 'gi2dimrtgmge' does not exist", 'file': 'transaction_context.cpp', 'line_number': 641, 'method': 'validate_referenced_accounts'}]}}

Process finished with exit code 1

**Comment by ShilazTech** [comment]
I checked on eostracker - the account gi2dimrtgmge exists

**Comment by deckb** [comment]
You are trying to push the transaction to my personal testnet which does not have that account.

```
/usr/bin/cleos -u http://api.pennstation.eosnewyork.io:7001 get account gi2dimrtgmge

error 2019-01-30T12:54:00.307 thread-0  main.cpp:3449                 main                 ] Failed with error: unspecified (0)
unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 gi2dimrtgmge)
```
You need to point to a mainnet endpoint. I suggest using the proxy https://eosnode.tools/proxy

**Comment by ShilazTech** [comment]
I used the proxy account and now i get below error message

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://proxy.eosnode.tools/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/eos.py", line 31, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 173, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure', 'details': [{'message': 'assertion failure with message: to account does not exist', 'file': 'wasm_interface.cpp', 'line_number': 917, 'method': 'eosio_assert'}, {'message': 'pending console output: ', 'file': 'apply_context.cpp', 'line_number': 72, 'method': 'exec_one'}]}}

Process finished with exit code 1

**Comment by deckb** [comment]
It looks like whatever account you are trying transfer to does not exist:

"to account does not exist" 

Can you send over the to and from fields from the data?

**Comment by ShilazTech** [comment]
Below is what that I am using

arguments = {
            "from": "gi2dimrtgmge",  # sender
            "to": "betdiceadmin",  # receiver
            "quantity": '0.1 EOS',  # In EOS
            "memo": "action:bet,seed:QMCmH3yQOknMlmoDcW,rollUnder:50",
        }
payload  = {
            "account": "eosio.token",
            "name": "transfer",
            "authorization": [{
                "actor": "gi2dimrtgmge",
                "permission": "active",
            }],
        }

**Comment by deckb** [comment]
Here is the code that I just used to successfully submit a bet. Should work if you replace <youraccount> with your actual account.

```
import eospy.cleos
import os
 
ce = eospy.cleos.Cleos(url='https://proxy.eosnode.tools')

arguments = {
            "from": "<youraccount>",  # sender
            "to": "betdiceadmin",  # receiver
            "quantity": '0.1000 EOS',  # In EOS
            "memo": "action:bet,seed:QMCmH3yQOknMlmoDcW,rollUnder:50",
        }
payload = {
        "account": "eosio.token",
        "name": "transfer",
        "authorization": [{
            "actor": "<youraccount>",
            "permission": "active",
        }],
    }
#Converting payload to binary
data=ce.abi_json_to_bin(payload['account'],payload['name'],arguments)
#Inserting payload binary form as "data" field in original payload
payload['data']=data['binargs']
#final transaction formed
trx = {"actions": [payload]}

script_dir = os.path.dirname(os.path.realpath(__file__))
key_file = os.path.join(script_dir,'account.key')

resp = ce.push_transaction(trx, key_file, broadcast=True)
print('------------------------------------------------')
print(resp)
print('------------------------------------------------')
```

**Comment by ShilazTech** [comment]
Now I am receiving below error

Traceback (most recent call last):
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/eos.py", line 30, in <module>
    resp = ce.push_transaction(trx, key_file, broadcast=True)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 163, in push_transaction
    raise EOSKeyError('Must pass a WIF string or EOSKey')
eospy.exceptions.EOSKeyError: Must pass a WIF string or EOSKey

Process finished with exit code 1
 And I am using owner key.

**Comment by deckb** [comment]
I do not suggest that you use your owner key for these types of actions. It looks like the key you are passing is not in the correct format. If you are trying to use a key file make sure you are using the latest version of libeospy which should be:
```
pip freeze | grep libeospy
libeospy==1.1.10
```

**Comment by ShilazTech** [comment]
In your code inplace of account.key I am using my owner key. Don't you think that should work?

Could you suggest an app which can help me generate active key. Thanks for all your support.

**Comment by ShilazTech** [comment]
The above from python command line is successful but problem remains. What can be done?
