### ISSUE TITLE
run examples error

### ISSUE THREAD

**Issue by hmilymb** [eosnewyork/eospy#3]
$ python push_transaction.py
```
$ python push_transaction.py
{'binargs': '0000000000ea3055408608850c110e3d102700000000000004454f53000000000474657374'}
actions: {'actions': [{'account': 'eosio.token', 'name': 'transfer', 'authorization': [{'actor': 'eosio', 'permission': 'active'}], 'data': '0000000000ea3055408608850c110e3d102700000000000004454f53000000000474657374'}]}
Traceback (most recent call last):
  File "push_transaction.py", line 18, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\cleos.py", line 146, in push_transaction
    encoded = trx.encode()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 196, in encode
    hdr_buf = self._encode_hdr()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 184, in _encode_hdr
    exp = self._encode_buffer(UInt32(exp_ts))
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 81, in _encode_buffer
    return EOSBuffer(value).encode()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 248, in encode
    return self._write_number(val, 'I')
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 212, in _write_number
    le = convert_little_endian(val, format)
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 11, in convert_little_endian
    return struct.pack('<{}'.format(format), buf)
NameError: name 'struct' is not defined
```

**Comment by hmilymb** [comment]
nb@DESKTOP-4TJ6ASD MINGW64 /c/work/tmp/eospy/examples (master)
$ python push_transaction.py
{'binargs': '0000000000ea3055408608850c110e3d102700000000000004454f53000000000474657374'}
actions: {'actions': [{'account': 'eosio.token', 'name': 'transfer', 'authorization': [{'actor': 'eosio', 'permission': 'active'}], 'data': '0000000000ea3055408608850c110e3d102700000000000004454f53000000000474657374'}]}
Traceback (most recent call last):
  File "push_transaction.py", line 18, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\cleos.py", line 146, in push_transaction
    encoded = trx.encode()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 196, in encode
    hdr_buf = self._encode_hdr()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 184, in _encode_hdr
    exp = self._encode_buffer(UInt32(exp_ts))
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 81, in _encode_buffer
    return EOSBuffer(value).encode()
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 248, in encode
    return self._write_number(val, 'I')
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 212, in _write_number
    le = convert_little_endian(val, format)
  File "C:\Users\nb\AppData\Local\Programs\Python\Python36\lib\site-packages\eospy\types.py", line 11, in convert_little_endian
    return struct.pack('<{}'.format(format), buf)
NameError: name 'struct' is not defined

**Comment by deckb** [comment]
Sorry about that I refactored and forgot the import for struct. I am going to get some CI going for this project and also refactor some things. It should be fixed and works. Please note I am currently working on some wonkiness that is occurring when running with python 3
