### ISSUE TITLE
example push_transaction.py doesn't work

### ISSUE THREAD

**Issue by SteadyAction** [eosnewyork/eospy#30]
This is my code.

```import eospy.cleos

ce = eospy.cleos.Cleos(url="http://107.182.23.236:8888")
# ce = eospy.cleos.Cleos(url='http://api.pennstation.eosnewyork.io:7001')

arguments = {
            "from": "eosio",  # sender
            "to": "bob123451234",  # receiver
            "quantity": '1.0000 EOS',  # In EOS
            "memo": "EOS to the moon",
        }
payload = {
        "account": "eosio.token",
        "name": "transfer",
        "authorization": [{
            "actor": "eosio",
            "permission": "active",
        }],
    }
#Converting payload to binary
data=ce.abi_json_to_bin(payload['account'],payload['name'],arguments)
#Inserting payload binary form as "data" field in original payload
payload['data']=data['binargs']
#final transaction formed
trx = {"actions": [payload]}

# use a string or EOSKey for push_transaction
key = "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
# use EOSKey:
# import eospy.keys
# key = eospy.keys.EOSKey('5HuaTWKeGzZhqyzuzFAjjFjPnnnjdgcp562oBSS8Wv1qgDSkR2W')
resp = ce.push_transaction(trx, key, broadcast=True)
print('------------------------------------------------')
print(resp)
print('------------------------------------------------')
```

I tried multiple endpoints but always got same errors.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eospy/dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://107.182.23.236:8888/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 34, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "/usr/local/lib/python3.6/site-packages/eospy/cleos.py", line 173, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/eospy/cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/eospy/dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3090003, 'name': 'unsatisfied_authorization', 'what': 'Provided keys, permissions, and delays do not satisfy declared authorizations', 'details': [{'message': 'transaction declares authority \'{"actor":"eosio","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"], and a delay max limit of 3888000000 ms', 'file': 'authorization_manager.cpp', 'line_number': 520, 'method': 'check_authorization'}]}}
```

**Comment by deckb** [comment]
That is because you are trying to push to the Jungle testnet using the `eosio` account which has been given the `eosio.prods` permissions.  You need to change the `to` and `from` fields and pass the private key of the `from` account. 

```
"from": "<some_account_you_own>",  # sender
"to": "<some_real_account>",  # receiver
```
I would also suggest using the second example since it uses a key file in the format
```
Private Key: some private key
Public Key: some public key
```
