### ISSUE TITLE
getting disconnected  on regular basis

### ISSUE THREAD

**Issue by ShilazTech** [eosnewyork/eospy#34]
I am getting disconnceted with below error on regular basis. How to avoid this and keep connections on

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\R.K Tyagi\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:835: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='proxy.eosnode.tools', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/EOSbetdiceadminPredictorandTrader.py", line 482, in <module>
    whl(keyset,accountset,datafileP,datafilePTemp,count,countT,betvalue,newbetvalue,maxbet,nobtr,n_lags,nooutput,action)
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/EOSbetdiceadminPredictorandTrader.py", line 424, in whl
    rollahead = rollaheadme()
  File "C:/Users/R.K Tyagi/Documents/VulturesPick/EOS/EOSbetdiceadminPredictorandTrader.py", line 192, in rollaheadme
    timeout=30)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 132, in get_table
    return self.post('chain.get_table_rows', params=None, json=json, timeout=timeout)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\eospy\dynamic_url.py", line 39, in post_url
    r = requests.post(url,params=params, json=json, data=data, timeout=timeout)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\R.K Tyagi\PycharmProjects\MagicDice\venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='proxy.eosnode.tools', port=443): Read timed out. (read timeout=30)

Process finished with exit code 1

**Comment by deckb** [comment]
It has been brought to my attention when sharing this issue that your stacktrace appears to be showing that you are trying to game the eosbetadmin contract. I cannot in continue to help you attempting to game a dapp.
