### ISSUE TITLE
dublicate transaction

### ISSUE THREAD

**Issue by ChzenChzen** [eosnewyork/eospy#36]
I would like to push transaction with a high frequency, near 20 transactions in 10 seconds. When I start push transaction I get error :

```
Traceback (most recent call last):
  File "/Users/user/Documents/bla/venv/lib/python3.7/site-packages/eospy/dynamic_url.py", line 41, in post_url
    r.raise_for_status()
  File "/Users/user/Documents/bla/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://api.eosnewyork.io/v1/chain/push_transaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    resp = ce.push_transaction(trx, key, broadcast=True)
  File "/Users/user/Documents/bla/venv/lib/python3.7/site-packages/eospy/cleos.py", line 173, in push_transaction
    return self.post('chain.push_transaction', params=None, data=data, timeout=timeout)
  File "/Users/user/Documents/bla/venv/lib/python3.7/site-packages/eospy/cleos.py", line 33, in post
    return cmd.post_url(url, **kwargs)
  File "/Users/user/Documents/bla/venv/lib/python3.7/site-packages/eospy/dynamic_url.py", line 43, in post_url
    raise requests.exceptions.HTTPError('Error: {}'.format(r.json()))
requests.exceptions.HTTPError: Error: {'code': 409, 'message': 'Conflict', 'error': {'code': 3040008, 'name': 'tx_duplicate', 'what': 'Duplicate transaction', 'details': [{'message': 'duplicate transaction 2ada2e84a48aad72c6fcba7d3d014d40dd36b27079dd76d95b714f3cc0accf1d', 'file': 'producer_plugin.cpp', 'line_number': 409, 'method': 'process_incoming_transaction_async'}]}}
```

**Comment by zwca** [comment]
@ChzenChzen how to contact you?WeChat?

**Comment by ChzenChzen** [comment]
@zwca telegram: ChzChz

**Comment by zwca** [comment]
your telegram open mutual contacts

**Comment by deckb** [comment]
Hello, 
Essentially the whole transaction is serialized and the transaction id is the checksum of that serialized transaction. If you send a transaction with all the same fields the transaction id is the duplicated and the transaction fails (https://github.com/EOSIO/eos/issues/384). You can pass a new expiration for each transaction like this example (https://github.com/eosnewyork/eospy/blob/2db95ee30b946a94aab7ce476c45143e08817488/examples/push_transaction.py#L29).

**Comment by deckb** [comment]
closing as there has been no response.
