### ISSUE TITLE
"ImportError: cannot import name ABC"

### ISSUE THREAD

**Issue by spartucus** [eosnewyork/eospy#45]
OS: Mac 10.14.3, have both Python2.7 and Python3.x
library version: v2.0.0, installed with pip

run with python2
```
MacBook-Pro:examples oc$ python --version
Python 2.7.16
MacBook-Pro:examples oc$ python create_user.py 
Traceback (most recent call last):
  File "create_user.py", line 1, in <module>
    from eospy.cleos import Cleos
  File "/usr/local/lib/python2.7/site-packages/eospy/cleos.py", line 6, in <module>
    from .keys import EOSKey, check_wif
  File "/usr/local/lib/python2.7/site-packages/eospy/keys.py", line 7, in <module>
    from .signer import Signer
  File "/usr/local/lib/python2.7/site-packages/eospy/signer.py", line 1, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC
```

run with python3
```
MacBook-Pro:examples oc$ python3 --version
Python 3.7.3
MacBook-Pro:examples oc$ python3 create_user.py 
Traceback (most recent call last):
  File "create_user.py", line 1, in <module>
    from eospy.cleos import Cleos
ModuleNotFoundError: No module named 'eospy'
```

**Comment by spartucus** [comment]
well, maybe too early to use v2.0.0? v1.1.11 is ok.
