### ISSUE TITLE
AttributeError in example/push_transaction

### ISSUE THREAD

**Issue by jiap** [eosnewyork/eospy#56]
When using `example/push_transaction.py`, the prog shows error as follows,
```
$  python3 push_transaction.py
>  File "push_transaction.py", line 130, in <module>
>    vote_data = sys_abi.json_to_bin(vote_payload['name'], vote_params)
> AttributeError: 'Abi' object has no attribute 'json_to_bin'
```
(you can see in VOTE part)

However in `sys_abi (in eospy/types.py)`, there is `json_to_bin` function. What's happening? Can anyone help me?

**Comment by deckb** [comment]
You should be using the Cleos.abi_json_to_bin to convert the payload. The ABI is not fully functional yet.

https://github.com/eosnewyork/eospy/blob/ae7c6cc3aa0e85a4f78c13eaaa3f2672e1474b66/examples/push_transaction.py#L29

**Comment by jiap** [comment]
Thanks for replying. `data = ce.abi_json_to_bin(payload['account'], payload['name'], arguments) ` is ok. 

Here is my code. When running,  Line 57 error. 

```
import eospy.cleos
import eospy.keys
from eospy.types import Abi, Action
from eospy.utils import parse_key_file
import os
import pytz
import json


ce = eospy.cleos.Cleos(url='https://eos.greymass.com:443')

# use a string or EOSKey for push_transaction
# # use EOSKey:
key = eospy.keys.EOSKey('5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3')


script_dir = os.path.dirname(os.path.realpath(__file__))


########################################
# VOTE
########################################

abi_file = os.path.join(script_dir, 'eosio.system.abi')

with open(abi_file) as rf:
    abi_json = json.load(rf)
    sys_abi = Abi(abi_json)

    # wait to send transaction
    import time
    print('Pushing a vote after 2 seconds using abi file: {}'.format(abi_file))
    time.sleep(2)

    vote_payload = {
        "account": "eosio",
        "name": "voteproducer",
        "authorization": [{
            "actor": "eosaccount",
            "permission": "active",
        }],
    }

    vote_params = {
        "voter": "eosaccount",  # sender
        "proxy": "eosproxy",  # proxy
        "producers": []  # producers
    }

    # Voting Converting payload to binary
    data = ce.abi_json_to_bin(vote_payload['account'], vote_payload['name'], vote_params)
    print(data)


############################### Problem ######################################

    vote_data = sys_abi.json_to_bin(vote_payload['name'], vote_params)

############################### Problem   ######################################

    # Inserting payload binary form as "data" field in original payload
    vote_payload['data'] = vote_data
    print(vote_payload)
    # final transaction formed
    trx = {"actions": [vote_payload]}

    # resp = ce.push_transaction(trx, eospy.keys.EOSKey(key), broadcast=True)
    print('------------------------------------------------')
    print(resp)
    print('------------------------------------------------')

```

>  runing result:
```
Traceback (most recent call last):
  File "p.py", line 57, in <module>
    vote_data = sys_abi.json_to_bin(vote_payload['name'], vote_params)
AttributeError: 'Abi' object has no attribute 'json_to_bin'
```

**Comment by deckb** [comment]
What version of eospy are you running?

**Comment by jiap** [comment]
just git clone url, not use release edition.

**Comment by deckb** [comment]
I just ran the following using python 3.7 with master and it worked for me.

```
from eospy.types import Abi, Action
import json

abi_file = "/home/deck/Documents/git/eosnewyork/eospy/examples/eosio.system.abi"

with open(abi_file) as rf:
    abi_json = json.load(rf)
    sys_abi = Abi(abi_json)

    vote_payload = {
        "account": "eosio",
        "name": "voteproducer",
        "authorization": [{
            "actor": "eosaccount",
            "permission": "active",
        }],
    }

    vote_params = {
        "voter": "eosaccount",  # sender
        "proxy": "eosproxy",  # proxy
        "producers": []  # producers
    }

    data = sys_abi.json_to_bin(vote_payload['name'], vote_params)
    print(data)
```

**Comment by jiap** [comment]
maybe the different versions of the dependencies. I run in another mbp, it worked. Thanks for replying. (PS. this issue can close)
